{"stats": {"errors": 5, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 5}, "results": [{"classname": "index_test:TestSQLBasicOperations", "name": "test_alter_table", "time": 0.0010218620300292969, "type": "error", "errtype": "builtins.TypeError", "message": "'NoneType' object is not subscriptable", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/LoreDirick/sql-basic-operations-lab-nyc-career-ds-062518/test/index_test.py\", line 37, in test_alter_table\n    planets = altered_table.execute(\"SELECT name FROM sqlite_master WHERE type='table';\").fetchone()[0]\nTypeError: 'NoneType' object is not subscriptable\n"}, {"classname": "index_test:TestSQLBasicOperations", "name": "test_create_table", "time": 0.0003910064697265625, "type": "error", "errtype": "builtins.TypeError", "message": "'NoneType' object is not subscriptable", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/LoreDirick/sql-basic-operations-lab-nyc-career-ds-062518/test/index_test.py\", line 12, in test_create_table\n    planets = table.execute(\"SELECT name FROM sqlite_master WHERE type='table';\").fetchone()[0]\nTypeError: 'NoneType' object is not subscriptable\n"}, {"classname": "index_test:TestSQLBasicOperations", "name": "test_delete_from", "time": 0.00042247772216796875, "type": "error", "errtype": "sqlite3.OperationalError", "message": "no such table: planets", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/LoreDirick/sql-basic-operations-lab-nyc-career-ds-062518/test/index_test.py\", line 65, in test_delete_from\n    test_delete = deletion.execute(\"SELECT * FROM planets\").fetchall()\nsqlite3.OperationalError: no such table: planets\n"}, {"classname": "index_test:TestSQLBasicOperations", "name": "test_insert_into", "time": 0.0004954338073730469, "type": "error", "errtype": "sqlite3.OperationalError", "message": "no such table: planets", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/LoreDirick/sql-basic-operations-lab-nyc-career-ds-062518/test/index_test.py\", line 47, in test_insert_into\n    test = table_values.execute(\"SELECT * FROM planets\").fetchall()\nsqlite3.OperationalError: no such table: planets\n"}, {"classname": "index_test:TestSQLBasicOperations", "name": "test_update_jupiter", "time": 0.0005090236663818359, "type": "error", "errtype": "sqlite3.OperationalError", "message": "no such table: planets", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/LoreDirick/sql-basic-operations-lab-nyc-career-ds-062518/test/index_test.py\", line 58, in test_update_jupiter\n    self.assertEqual(table_values.execute(\"SELECT num_of_moons FROM planets WHERE name = 'Jupiter';\").fetchone()[0], result)\nsqlite3.OperationalError: no such table: planets\n"}]}